name: Test coverage
on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  contents: read
  checks: write
concurrency:
  group: coverage-${{ github.ref }}
  cancel-in-progress: true
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install coverage
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests with coverage (unittest)
        run: |
          python -m coverage run --source=paperank -m unittest discover -v -s tests -p 'test_*.py'
          python -m coverage xml
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false
        # If you install the Codecov GitHub App, no token is needed.
        # Otherwise, add:
        # env:
        #   CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}