name: Lint and type-check
on:
  push:
    branches: [ "main" ]
  pull_request:
permissions:
  contents: read
concurrency:
  group: lint-type-${{ github.ref }}
  cancel-in-progress: true
jobs:
  lint-type:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy ruff types-requests types-tqdm scipy-stubs
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Black (check)
        run: black --check .
      - name: isort (check)
        run: isort --profile black --check-only .
      - name: flake8
        run: flake8 . --count --max-line-length=127 --statistics
      - name: Ruff (lint)
        run: ruff check .
      - name: mypy
        run: mypy paperank