name: OpenSSF Scorecard

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "23 3 * * 0"  # weekly
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  security-events: write   # to upload SARIF to code scanning
  id-token: write          # to publish results to the Scorecard public API

jobs:
  analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: scorecard.sarif
          results_format: sarif
          publish_results: true

      - name: Upload SARIF to code scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: scorecard.sarif